import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {SidebarLayout} from "@/app/catalyst-components/sidebar-layout";
import {Navbar} from "@/app/catalyst-components/navbar";
import {
    Sidebar,
    SidebarBody,
    SidebarHeader,
    SidebarHeading,
    SidebarItem,
    SidebarLabel, SidebarSection
} from "@/app/catalyst-components/sidebar";
import {NewspaperIcon} from "@heroicons/react/20/solid";
import {Avatar} from "@/app/catalyst-components/avatar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarLayout
            navbar={
                <Navbar>
                </Navbar>
            }
            sidebar={
                <Sidebar>
                    <SidebarHeader>
                        <SidebarItem href="/">
                            <Avatar src={'/general/react.svg'} alt={'react-logo'} />
                            <SidebarLabel>JMA Web Portfolio</SidebarLabel>
                        </SidebarItem>
                    </SidebarHeader>
                    <SidebarBody>
                        <SidebarSection>
                            <SidebarHeading>Projects</SidebarHeading>
                            <SidebarItem href="/projects/recipe-page">
                                <NewspaperIcon />
                                <SidebarLabel>Recipe Page</SidebarLabel>
                            </SidebarItem>
                        </SidebarSection>
                    </SidebarBody>
                </Sidebar>
            }
        >
            {children}
        </SidebarLayout>
      </body>
    </html>
  );
}
